import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";


const CollectionPage: NextPage = () => {
  const icons = api.icons.getIcons.useQuery();

  return (
    <>
      <Head>
        <title>Your Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto my-10 gap-4 flex flex-col px-4">
        <h1 className="text-3xl mt-2 mb-10">Your Icons</h1>
        <ul className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 gap-4">
          {icons.data?.map(icon => (
            <li key={icon.id}>
              <Image src={`https://icon-generator-icons.s3.us-east-2.amazonaws.com/${icon.id}`} width="100" height="100" alt={icon.prompt ?? "img of an icon"} className="rounded-lg w-full" />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default CollectionPage;

