import { type NextPage } from "next";
import Head from "next/head";

import { PrimaryLinkButton } from "~/component/PrimaryLinkButton";

function HeroBanner() {

  return <section className="my-24 flex flex-col gap-2 items-start">
    <h1 className="text-6xl py-1 font-bold">Icon Generator</h1>
    <p className="text-2xl pb-6 font-medium">Use AI to generate icons in one easy step</p>
    <PrimaryLinkButton href='/generate'>
      Get started
    </PrimaryLinkButton>
  </section>;
}

const HomePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-10">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
